# Generated by Django 4.0.2 on 2022-02-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('readMore', models.TextField()),
            ],
        ),
    ]
